#!/usr/bin/env bash
# generate_lyrics_v5.5.sh — Sodium Lights — pack: suno_sodium_lights
#
# Exact pp-cli invocation for lyrics_v5.5.md (single v5.x style block).
# Generated by suno-pack; keep in sync when prompts change.
#
# SPENDS CREDITS. Never uses --download (title-named files collide and
# overwrite paid takes); downloads per clip id with take-aware rename.
set -euo pipefail

PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROMPT_NAME="lyrics_v5.5.md"
PROMPT_FILE="$PACK_DIR/$PROMPT_NAME"
SLUG="sodium_lights"
MODEL="v5.5"
WEIRDNESS=35
STYLE_INFLUENCE=65
INSTRUMENTAL=0                       # Settings: Instrumental toggle OFF
STYLE_SECTION='^## Style of Music'   # single style block (v5.x)
VARIANT=""
EST_COST="~10 credits for 2 takes (assumed; v5.5 cost unverified — confirm via credits before/after)"

command -v suno-pp-cli >/dev/null 2>&1 || {
  echo "suno-pp-cli not found. Install (no sudo):" >&2
  echo "  npx -y @mvanhorn/printing-press-library install suno" >&2
  exit 1
}
command -v jq >/dev/null 2>&1 || { echo "jq is required to parse clip ids" >&2; exit 1; }
[[ -f "$PROMPT_FILE" ]] || { echo "missing prompt file: $PROMPT_FILE" >&2; exit 1; }

extract_fenced() { # $1: regex matching the section heading line
  awk -v sec="$1" '
    !insec && $0 ~ sec { insec = 1; next }
    insec && /^```/    { if (infence) exit; infence = 1; next }
    infence            { print }
  ' "$PROMPT_FILE"
}

TITLE="$(extract_fenced '^## Title')"
LYRICS="$(extract_fenced '^## Lyrics')"
EXCLUDE="$(extract_fenced '^## Exclude Styles')"
STYLE="$(extract_fenced "$STYLE_SECTION")"
for v in TITLE LYRICS STYLE; do
  [[ -n "${!v}" ]] || { echo "extraction failed: $v from $PROMPT_NAME" >&2; exit 1; }
done

INSTR_LABEL=OFF; [[ "$INSTRUMENTAL" -eq 1 ]] && INSTR_LABEL=ON
echo "================================================================"
echo " suno-pack execute — $PROMPT_NAME (pack: $SLUG)"
echo "   Model $MODEL | Weirdness ${WEIRDNESS}% | Style Influence ${STYLE_INFLUENCE}% | Instrumental $INSTR_LABEL"
echo "   Style variant: ${VARIANT:-single block}"
echo "   Title: $TITLE"
echo " COST WARNING: this spends real credits — $EST_COST."
echo " Exclude caveat: --exclude is passed but the CLI sends"
echo " negative_tags empty; exclude enforcement needs the web UI."
echo "================================================================"

if [[ "${1:-}" != "--yes" ]]; then
  read -r -p "Spend credits and generate now? Type 'yes' to proceed: " REPLY
  [[ "$REPLY" == "yes" ]] || { echo "Aborted — nothing spent."; exit 1; }
fi

CREDITS_BEFORE="$(suno-pp-cli --agent credits | jq -r '.credits // 0')"

ARGS=(--json --yes generate create
  --title "$TITLE"
  --lyrics "$LYRICS"
  --tags "$STYLE"
  --exclude "$EXCLUDE"
  --model "$MODEL"
  --weirdness "$WEIRDNESS" --style-influence "$STYLE_INFLUENCE"
  --wait)
[[ "$INSTRUMENTAL" -eq 1 ]] && ARGS+=(--instrumental)

# Free preflight — validates flags, sends nothing.
suno-pp-cli --dry-run "${ARGS[@]}" >/dev/null

RESPONSE="$(suno-pp-cli "${ARGS[@]}")"

mapfile -t CLIP_IDS < <(jq -r '(.data.clips // .clips // [])[].id' <<<"$RESPONSE")
[[ "${#CLIP_IDS[@]}" -gt 0 ]] || {
  echo "No clip ids in response — raw response follows:" >&2
  printf '%s\n' "$RESPONSE" >&2
  exit 1
}

mkdir -p "$PACK_DIR/audio" "$PACK_DIR/runs"
CLIPS_JSON="[]"
N=0
for CLIP_ID in "${CLIP_IDS[@]}"; do
  N=$((N + 1))
  TMP="$(mktemp -d "$PACK_DIR/audio/.dl.XXXXXX")"
  suno-pp-cli download "$CLIP_ID" --out "$TMP/" >/dev/null
  SRC="$(find "$TMP" -type f | head -n 1)"
  [[ -n "$SRC" ]] || { echo "download produced no file for $CLIP_ID" >&2; exit 1; }
  EXT="${SRC##*.}"
  DEST="$PACK_DIR/audio/${SLUG}-${MODEL}-take${N}-${CLIP_ID:0:8}.${EXT}"
  mv "$SRC" "$DEST"
  rmdir "$TMP" 2>/dev/null || true
  echo "take $N -> $DEST"
  RESP_CLIP="$(jq -c --arg id "$CLIP_ID" \
    '[(.data.clips // .clips // [])[] | select(.id == $id)] | first
     | {model_name: (.model_name // null), created_at: (.created_at // null)}' \
    <<<"$RESPONSE")"
  CLIPS_JSON="$(jq -c --arg id "$CLIP_ID" --arg f "audio/$(basename "$DEST")" \
    --argjson rc "$RESP_CLIP" \
    '. + [{clip_id: $id} + $rc + {file: $f}]' <<<"$CLIPS_JSON")"
done

# Two takes, two files, always — verify before reporting.
while read -r f; do
  [[ -s "$PACK_DIR/$f" ]] || { echo "MISSING downloaded file: $f" >&2; exit 1; }
done < <(jq -r '.[].file' <<<"$CLIPS_JSON")

CREDITS_AFTER="$(suno-pp-cli --agent credits | jq -r '.credits // 0')"
LYRICS_SHA="$(printf '%s' "$LYRICS" | sha256sum | cut -c1-10)"
STYLE_SHA="$(printf '%s' "$STYLE" | sha256sum | cut -c1-10)"
TS="$(date -u +%Y-%m-%dT%H-%M-%SZ)"
RUN_LOG="$PACK_DIR/runs/${TS}-${PROMPT_NAME%.md}.json"
CLI_ARGS_JSON="$(jq -cn '$ARGS.positional' --args "${ARGS[@]}")"

jq -n \
  --arg pack "$SLUG" --arg pf "$PROMPT_NAME" --arg variant "$VARIANT" \
  --arg model "$MODEL" \
  --argjson weirdness "$WEIRDNESS" --argjson si "$STYLE_INFLUENCE" \
  --argjson instrumental "$([[ "$INSTRUMENTAL" -eq 1 ]] && echo true || echo false)" \
  --argjson cli_args "$CLI_ARGS_JSON" \
  --arg lsha "$LYRICS_SHA" --arg ssha "$STYLE_SHA" \
  --argjson clips "$CLIPS_JSON" \
  --argjson cb "${CREDITS_BEFORE:-0}" --argjson ca "${CREDITS_AFTER:-0}" \
  '{
    request: {
      pack: $pack, prompt_file: $pf,
      variant: (if $variant == "" then null else $variant end),
      settings: {model: $model, weirdness: $weirdness,
                 style_influence: $si, instrumental: $instrumental},
      cli_args: $cli_args,
      lyrics_sha256: $lsha, style_sha256: $ssha,
      sliders_not_cli_settable: null
    },
    result: {clips: $clips, credits_before: $cb,
             credits_after: $ca, captcha: "open"},
    human_scorecard: {}
  }' > "$RUN_LOG"

suno-pp-cli --agent sync --latest-only >/dev/null 2>&1 || true
echo "----------------------------------------------------------------"
echo "Done. Credits: $CREDITS_BEFORE -> $CREDITS_AFTER"
echo "Run log: $RUN_LOG"
echo "Listen and judge the takes yourself — this script has no ears."
